/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.EMSController;
import model.EMSFactory;
import model.dto.EmployeeDTO;
import model.dto.Response;

/**
 *
 * @author fawad
 */
public class EmployeeDashboard extends javax.swing.JPanel {

    private ArrayList<EmployeeDTO> employeList;
    private EMSController controller;

    /**
     * Creates new form EmployeeDashboard
     */
    public EmployeeDashboard() {
        initComponents();
        controller = EMSFactory.getInstanceofEMSController();
        updateTable();
        populateDataIntoViewEmployeeTable();
    }
    private void updateTable(){
        employeList = controller.getEmployees(new Response());
        System.out.println(employeList);
    }
    private void populateDataIntoViewEmployeeTable() {
       
        DefaultTableModel model = (DefaultTableModel) viewemployeeTable.getModel();
        model.setRowCount(0); // Clear existing table data

        for (EmployeeDTO employee : employeList) {
            Object[] rowData = {employee.getId(), employee.getName(), employee.getAge(), employee.getDepartment()};
            model.addRow(rowData); // Add each employee as a row in the table
        }
        viewemployeeTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        EmployeeManagement = new javax.swing.JTabbedPane();
        viewEmployee = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewemployeeTable = new javax.swing.JTable();
        addEmployee = new javax.swing.JPanel();
        editEmployee = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        viewEmployee.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employees Table");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 287;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel5.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Search Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 93, 0, 0);
        jPanel5.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 34, 11, 0);
        jPanel5.add(searchName, gridBagConstraints);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        viewemployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Department" // Update column names here
            }
        ));
        jScrollPane1.setViewportView(viewemployeeTable);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        viewEmployee.add(jPanel4, java.awt.BorderLayout.CENTER);

        EmployeeManagement.addTab("View", viewEmployee);

        javax.swing.GroupLayout addEmployeeLayout = new javax.swing.GroupLayout(addEmployee);
        addEmployee.setLayout(addEmployeeLayout);
        addEmployeeLayout.setHorizontalGroup(
            addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        addEmployeeLayout.setVerticalGroup(
            addEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        EmployeeManagement.addTab("Add", addEmployee);

        javax.swing.GroupLayout editEmployeeLayout = new javax.swing.GroupLayout(editEmployee);
        editEmployee.setLayout(editEmployeeLayout);
        editEmployeeLayout.setHorizontalGroup(
            editEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        editEmployeeLayout.setVerticalGroup(
            editEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        EmployeeManagement.addTab("Edit", editEmployee);

        add(EmployeeManagement, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane EmployeeManagement;
    private javax.swing.JPanel addEmployee;
    private javax.swing.JPanel editEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchName;
    private javax.swing.JPanel viewEmployee;
    private javax.swing.JTable viewemployeeTable;
    // End of variables declaration//GEN-END:variables
}
